"""Checksum the publication tables and figures generated by the workflow."""
from __future__ import annotations

import hashlib
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def main() -> None:
    output = ROOT / "results" / "output_manifest.csv"
    files = [
        path for folder in (ROOT / "results", ROOT / "figures")
        for path in folder.rglob("*")
        if path.is_file() and path != output and not path.name.startswith(".")
    ]
    rows = [{
        "path": str(path.relative_to(ROOT)),
        "bytes": path.stat().st_size,
        "sha256": digest(path),
    } for path in sorted(files)]
    pd.DataFrame(rows).to_csv(output, index=False)
    print(f"Wrote {len(rows)} output checksums to {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
